name: Deploy Production
on: 
    push:
        tags: 
            - v[0-9]+.[0-9]+.[0-9]+

env:
  - APP_NAME: "gitops-fontend"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Container
              run: |
                IMAGE_TAG="${GITHUB_REF#refs/*/}"

                IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${IMAGE_TAG}"

                docker build -f ./Dockerfile -t "${IMAGE_NAME}" .
                docker push "${IMAGE_NAME}"